POST http://localhost:3333/courses
Content-Type: application/json

{
    "title":"Curso Node.js com Docker"
}


###

GET http://localhost:3333/courses
###

GET http://localhost:3333/courses/b6f0731a-8ab1-40da-a7c9-bfbb35cc4b0f